version: '3.1'

services:
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - "tfm-db:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: qwjkl5,4
    ports:
      - "127.0.0.1:27017:27017"

volumes:
  tfm-db:
    external: true
