version: '3.8'

services:
  postgres:
    container_name: tfm-malware-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_DATABASE}
    volumes:
      - ./postgresql-creation.sql:/docker-entrypoint-initdb.d/init.sql
      - "tfm-malware-db:/var/lib/postgresql/data"
    ports:
      - "127.0.0.1:5432:5432"
    restart: unless-stopped
    env_file:
      - ../.env
  server:
    container_name: tfm-malware-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./wait-for-it.sh", "postgres:5432", "--", "pm2-runtime", "start", "pm2.config.js"]
    volumes:
      - ../pm2-logs:/tfm-malware-api/pm2-logs
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - postgres
    links:
      - postgres
    env_file:
      - ../.env
volumes:
  tfm-malware-db:
    external: true
